[build]
# TODOdin: Fix netlify config such that we don't need this file
# and netlify.toml in frontend/ is enough
base = "frontend"
command = "cd frontend;pnpm i && pnpm run build"
publish = "frontend/dist"
